package ai.minecivilization.construction;

import java.util.ArrayList;
import java.util.List;

/**
 * The built-in "Animal Pen" blueprint: a fenced square with a gate.
 *
 * <p>Generated by this project, like the other built-ins — no downloaded
 * schematics, no licensing questions.</p>
 *
 * <p>The only thing that matters about a pen is that it actually holds: a fence
 * ring one block high, unbroken except for a gate, with the fence standing on
 * the ground rather than floating over it. Animals escape through exactly two
 * mistakes — a gap in the ring, and a fence placed a block too high — so the
 * ring is generated as a closed loop and the builder places it at ground
 * level.</p>
 */
public final class AnimalPen {
    public static final String ID = "animal_pen";

    /** Inside width of the pen. Nine by nine comfortably holds a few pairs. */
    public static final int SIZE = 9;

    private AnimalPen() {
    }

    public static boolean isPen(String id) { return id != null && (id.equals(ID) || id.startsWith(ID + "_")); }
    public static Blueprint create() { return create("oak"); }
    public static Blueprint create(String wood) {
        List<Blueprint.BlockEntry> entries = new ArrayList<>();
        int max = SIZE - 1;

        // The gate sits in the middle of the south wall, so citizens always
        // have one known way in and out.
        int gateX = SIZE / 2;

        for (int x = 0; x < SIZE; x++) {
            for (int z = 0; z < SIZE; z++) {
                boolean edge = x == 0 || z == 0 || x == max || z == max;
                if (!edge) continue;

                if (z == max && x == gateX) {
                    entries.add(new Blueprint.BlockEntry(x, 0, z,
                            "minecraft:" + wood + "_fence_gate[facing=south]"));
                } else {
                    entries.add(new Blueprint.BlockEntry(x, 0, z, "minecraft:" + wood + "_fence"));
                }
            }
        }

        // A torch on each corner post: livestock that can be seen at night is
        // livestock that does not quietly vanish to a zombie.
        entries.add(new Blueprint.BlockEntry(0, 1, 0, "minecraft:torch"));
        entries.add(new Blueprint.BlockEntry(max, 1, 0, "minecraft:torch"));
        entries.add(new Blueprint.BlockEntry(0, 1, max, "minecraft:torch"));
        entries.add(new Blueprint.BlockEntry(max, 1, max, "minecraft:torch"));

        return new Blueprint(wood.equals("oak") ? ID : ID + "_" + wood, "Animal Pen", SIZE, 2, SIZE, entries);
    }

    /** Where the gate sits, relative to the blueprint origin. */
    public static int gateOffsetX() {
        return SIZE / 2;
    }

    public static int gateOffsetZ() {
        return SIZE - 1;
    }
}
