package ai.minecivilization.construction;

import java.util.ArrayList;
import java.util.List;

/**
 * The built-in "Starter House" blueprint (~5x4x5): a compact one-room home
 * generated by this project — not downloaded, no copyright issues.
 *
 * <p>Lay-out (top view, y grows up):</p>
 * <pre>
 *  oak plank floor (5x4), log corners, plank walls with a 1-wide doorway on
 *  the south side, a crafting table inside for the household, plank roof.
 * </pre>
 *
 * <p>No glass and no door block: citizens can only realistically produce
 * planks, logs and crafting tables early on, and a lone lower door half
 * cannot be placed by the block-by-block builder.</p>
 */
public final class StarterHouse {
    public static final String ID = "starter_house";

    private StarterHouse() {
    }

    public static Blueprint create() {
        int sx = 5;
        int sz = 4;
        int wallHeight = 3;   // walls y=1..3, roof at y=4 -> sizeY 5
        List<Blueprint.BlockEntry> entries = new ArrayList<>();

        // Floor (y=0): oak planks everywhere — also the support for the table.
        for (int x = 0; x < sx; x++) {
            for (int z = 0; z < sz; z++) {
                entries.add(new Blueprint.BlockEntry(x, 0, z, "minecraft:oak_planks"));
            }
        }

        // Interior workstation right after the floor (support exists immediately).
        entries.add(new Blueprint.BlockEntry(1, 1, 1, "minecraft:crafting_table"));

        // Walls: log corners for the frame, planks in between, doorway in the
        // middle of the south wall (1 wide x 2 tall, lintel on top).
        for (int y = 1; y <= wallHeight; y++) {
            for (int x = 0; x < sx; x++) {
                for (int z = 0; z < sz; z++) {
                    boolean perimeter = x == 0 || x == sx - 1 || z == 0 || z == sz - 1;
                    if (!perimeter) continue;
                    if (z == sz - 1 && x == sx / 2 && y <= 2) continue; // doorway
                    boolean corner = (x == 0 || x == sx - 1) && (z == 0 || z == sz - 1);
                    entries.add(new Blueprint.BlockEntry(x, y, z,
                            corner ? "minecraft:oak_log" : "minecraft:oak_planks"));
                }
            }
        }

        // Roof (y=4): full plank lid.
        int roofY = wallHeight + 1;
        for (int x = 0; x < sx; x++) {
            for (int z = 0; z < sz; z++) {
                entries.add(new Blueprint.BlockEntry(x, roofY, z, "minecraft:oak_planks"));
            }
        }

        return new Blueprint(ID, "Starter House", sx, roofY + 1, sz, entries);
    }
}
