package ai.minecivilization.construction;

import java.util.ArrayList;
import java.util.List;

/**
 * The built-in original test blueprint: "Starter Warehouse" (~9x6x7).
 * Generated by this project — not downloaded, no copyright issues.
 *
 * <p>Lay-out (top view, y grows up):</p>
 * <pre>
 *  stone brick floor (9x7), plank walls with a 2-wide door gap on the south
 *  side, glass windows on each long side, plank roof at the top.
 * </pre>
 */
public final class StarterWarehouse {
    public static final String ID = "starter_warehouse";

    private StarterWarehouse() {
    }

    public static Blueprint create() {
        int sx = 9;
        int sz = 7;
        int wallHeight = 5; // floor at y=0, walls y=1..5, roof at y=6 -> height 7 total? spec ~6
        List<Blueprint.BlockEntry> entries = new ArrayList<>();

        // Build order: floor (center-out) -> walls bottom-up -> roof.
        // Floor: stone bricks 9x7
        for (int y = 0; y <= 0; y++) {
            for (int ring = 0; ring < Math.max(sx, sz); ring++) {
                for (int x = 0; x < sx; x++) {
                    for (int z = 0; z < sz; z++) {
                        int d = Math.min(Math.min(x, sx - 1 - x), Math.min(z, sz - 1 - z));
                        if (d != ring && !(ring >= Math.min(sx, sz) / 2 && d == ring)) continue;
                        if (d != ring) continue;
                        entries.add(new Blueprint.BlockEntry(x, y, z, "minecraft:stone_bricks"));
                    }
                }
            }
        }

        // Walls
        for (int y = 1; y <= wallHeight; y++) {
            for (int x = 0; x < sx; x++) {
                for (int z = 0; z < sz; z++) {
                    boolean perimeter = x == 0 || x == sx - 1 || z == 0 || z == sz - 1;
                    if (!perimeter) continue;
                    boolean south = z == sz - 1;
                    // 2-wide door gap in the middle of the south wall (ground level)
                    if (south && y <= 2 && (x == 4 || x == 5)) continue;
                    // windows: middle height on east/west walls
                    boolean side = (x == 0 || x == sx - 1) && z > 1 && z < sz - 2;
                    if (side && y == 3) {
                        entries.add(new Blueprint.BlockEntry(x, y, z, "minecraft:glass_pane"));
                        continue;
                    }
                    entries.add(new Blueprint.BlockEntry(x, y, z, "minecraft:oak_planks"));
                }
            }
        }

        // Roof
        int roofY = wallHeight + 1;
        for (int x = 0; x < sx; x++) {
            for (int z = 0; z < sz; z++) {
                boolean edge = x == 0 || x == sx - 1 || z == 0 || z == sz - 1;
                entries.add(new Blueprint.BlockEntry(x, roofY, z,
                        edge ? "minecraft:oak_planks" : "minecraft:oak_slab"));
            }
        }

        return new Blueprint(ID, "Starter Warehouse", sx, roofY + 1, sz, entries);
    }
}
