package ai.minecivilization.construction;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The built-in Starter Warehouse is generated by code (original work, no
 * downloaded schematics). These tests pin down its shape so a refactor cannot
 * silently ship a broken or unpublishable blueprint.
 */
class StarterWarehouseTest {

    private final Blueprint bp = StarterWarehouse.create();

    @Test
    void metadataMatchesSpec() {
        assertEquals(StarterWarehouse.ID, bp.id);
        assertEquals("Starter Warehouse", bp.name);
        assertEquals(9, bp.sizeX);
        assertEquals(7, bp.sizeZ);
        assertTrue(bp.blockCount() > 100, "warehouse should be a real structure");
    }

    @Test
    void everyEntryIsInsideTheBlueprintBounds() {
        for (Blueprint.BlockEntry e : bp.entries()) {
            assertTrue(e.x >= 0 && e.x < bp.sizeX, "x out of bounds: " + e.x);
            assertTrue(e.y >= 0 && e.y < bp.sizeY, "y out of bounds: " + e.y);
            assertTrue(e.z >= 0 && e.z < bp.sizeZ, "z out of bounds: " + e.z);
        }
    }

    @Test
    void noPositionIsBuiltTwice() {
        Set<String> positions = new HashSet<>();
        for (Blueprint.BlockEntry e : bp.entries()) {
            assertTrue(positions.add(e.x + "," + e.y + "," + e.z),
                    "duplicate block position " + e.x + "," + e.y + "," + e.z);
        }
        assertEquals(bp.blockCount(), positions.size());
    }

    @Test
    void floorIsStoneBricksAndFullyPaved() {
        int floor = 0;
        for (Blueprint.BlockEntry e : bp.entries()) {
            if (e.y != 0) continue;
            assertEquals("minecraft:stone_bricks", e.blockState);
            floor++;
        }
        assertEquals(9 * 7, floor, "the 9x7 floor must be fully paved");
    }

    @Test
    void southWallHasATwoWideDoorGap() {
        int southZ = bp.sizeZ - 1;
        for (Blueprint.BlockEntry e : bp.entries()) {
            // the floor (y=0) runs to the wall; the gap is in the walls only
            if (e.z != southZ || e.y < 1 || e.y > 2) continue;
            assertFalse((e.x == 4 || e.x == 5),
                    "door gap blocked at x=" + e.x + " y=" + e.y);
        }
    }

    @Test
    void hasGlassWindows() {
        long windows = bp.entries().stream()
                .filter(e -> "minecraft:glass_pane".equals(e.blockState))
                .count();
        assertTrue(windows >= 4, "expected windows on the long sides, found " + windows);
    }

    @Test
    void billOfMaterialsCoversEveryPlacedBlock() {
        Map<String, Integer> bom = bp.billOfMaterials();
        int total = bom.values().stream().mapToInt(Integer::intValue).sum();
        assertEquals(bp.blockCount(), total);
        assertTrue(bom.containsKey("minecraft:oak_planks"));
        assertTrue(bom.containsKey("minecraft:stone_bricks"));
    }
}
