package ai.minecivilization.construction;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The built-in Starter House is generated by code (original work, no
 * downloaded schematics). These tests pin down its shape: a real 5x4 home
 * with a floor, a doorway, log corners and an interior workstation —
 * buildable from planks, logs and one crafting table.
 */
class StarterHouseTest {

    private final Blueprint bp = StarterHouse.create();

    @Test
    void metadataMatchesSpec() {
        assertEquals(StarterHouse.ID, bp.id);
        assertEquals("Starter House", bp.name);
        assertEquals(5, bp.sizeX);
        assertEquals(4, bp.sizeZ);
        assertEquals(5, bp.sizeY);
        // floor 20 + table 1 + walls (14x3 - 2 doorway) 40 + roof 20
        assertEquals(81, bp.blockCount());
    }

    @Test
    void everyEntryIsInsideTheBlueprintBounds() {
        for (Blueprint.BlockEntry e : bp.entries()) {
            assertTrue(e.x >= 0 && e.x < bp.sizeX, "x out of bounds: " + e.x);
            assertTrue(e.y >= 0 && e.y < bp.sizeY, "y out of bounds: " + e.y);
            assertTrue(e.z >= 0 && e.z < bp.sizeZ, "z out of bounds: " + e.z);
        }
    }

    @Test
    void noPositionIsBuiltTwice() {
        Set<String> positions = new HashSet<>();
        for (Blueprint.BlockEntry e : bp.entries()) {
            assertTrue(positions.add(e.x + "," + e.y + "," + e.z),
                    "duplicate block position " + e.x + "," + e.y + "," + e.z);
        }
        assertEquals(bp.blockCount(), positions.size());
    }

    @Test
    void floorIsOakPlanksAndFullyPaved() {
        int floor = 0;
        for (Blueprint.BlockEntry e : bp.entries()) {
            if (e.y != 0) continue;
            assertEquals("minecraft:oak_planks", e.blockState);
            floor++;
        }
        assertEquals(5 * 4, floor, "the 5x4 floor must be fully paved");
    }

    @Test
    void southWallHasAOneWideDoorway() {
        int southZ = bp.sizeZ - 1;
        int centerX = bp.sizeX / 2;
        boolean doorwayOpen = true;
        for (Blueprint.BlockEntry e : bp.entries()) {
            if (e.z != southZ || e.y < 1 || e.y > 2) continue;
            if (e.x == centerX) doorwayOpen = false;
        }
        assertTrue(doorwayOpen, "the doorway at x=" + centerX + " must stay open");
        // lintel above the doorway keeps the wall (and roof) supported
        assertTrue(bp.entries().stream().anyMatch(
                        e -> e.x == centerX && e.y == 3 && e.z == southZ),
                "the doorway needs a lintel block on top");
    }

    @Test
    void hasInteriorCraftingTable() {
        long tables = bp.entries().stream()
                .filter(e -> "minecraft:crafting_table".equals(e.blockState))
                .count();
        assertEquals(1, tables, "one household workstation, placed at (1,1,1)");
        assertTrue(bp.entries().stream().anyMatch(
                e -> e.x == 1 && e.y == 1 && e.z == 1
                        && "minecraft:crafting_table".equals(e.blockState)),
                "the crafting table must stand inside on the floor");
    }

    @Test
    void cornersAreLogFramed() {
        long logs = bp.entries().stream()
                .filter(e -> "minecraft:oak_log".equals(e.blockState))
                .count();
        assertEquals(12, logs, "4 corner posts x 3 wall levels");
        for (int y = 1; y <= 3; y++) {
            assertTrue(hasLog(0, y, 0) && hasLog(bp.sizeX - 1, y, 0)
                    && hasLog(0, y, bp.sizeZ - 1) && hasLog(bp.sizeX - 1, y, bp.sizeZ - 1),
                    "missing log corner at y=" + y);
        }
    }

    @Test
    void roofIsFullyPaved() {
        int roof = 0;
        for (Blueprint.BlockEntry e : bp.entries()) {
            if (e.y != bp.sizeY - 1) continue;
            assertEquals("minecraft:oak_planks", e.blockState);
            roof++;
        }
        assertEquals(5 * 4, roof, "the roof must close the house completely");
    }

    @Test
    void billOfMaterialsCoversEveryPlacedBlock() {
        Map<String, Integer> bom = bp.billOfMaterials();
        int total = bom.values().stream().mapToInt(Integer::intValue).sum();
        assertEquals(bp.blockCount(), total);
        assertEquals(68, bom.get("minecraft:oak_planks"));
        assertEquals(12, bom.get("minecraft:oak_log"));
        assertEquals(1, bom.get("minecraft:crafting_table"));
    }

    private boolean hasLog(int x, int y, int z) {
        return bp.entries().stream().anyMatch(
                e -> e.x == x && e.y == y && e.z == z
                        && "minecraft:oak_log".equals(e.blockState));
    }
}
