package ai.minecivilization.skills;

/** The full V1 skill registry — new skills are added here only. */
public enum SkillType {
    IDLE,
    MOVE_TO,
    TRAVERSE,
    FOLLOW,
    FIND_BLOCK,
    MINE_BLOCK,
    MINE_AREA,
    FELL_TREE,
    DIG_MINE,
    PICKUP_ITEM,
    PLACE_BLOCK,
    HARVEST_CROP,
    PLANT_CROP,
    CULTIVATE,
    LIGHT_FARM,
    FORAGE,
    TILL_SOIL,
    TEND_LIVESTOCK,
    TAME_WOLF,
    PREPARE_PEN,
    HERD_ANIMAL,
    BREED_ANIMALS,
    HUNT,
    DECORATE,
    CRAFT_ITEM,
    SMELT_ITEM,
    DEPOSIT_ITEM,
    WITHDRAW_ITEM,
    EAT,
    SLEEP,
    BUILD_BLUEPRINT,
    DELIVER_ITEMS
}
